#!/bin/bash


echo Installing Bennu Json...
cd bennu-json
mvn clean install -q
cd ..

echo Installing Bennu Maven Plugin...
cd maven/bennu-maven-plugin/
mvn clean install -q
cd ../../

echo Installing Bennu Project...
cd bennu-project
mvn clean install -q
cd ..

echo Installing Bennu Service Annotation...
cd bennu-service
mvn clean install -q
cd ..

echo Installing Bennu Core...
cd bennu-core
mvn clean install -q
cd ..

echo Installing Bennu File Support...
cd bennu-filesupport
mvn clean install -q
cd ..

echo Installing Bennu Search...
cd bennu-search
mvn clean install -q
cd ..

echo Installing Bennu Dispatch...
cd bennu-dispatch
mvn clean install -q
cd ..

echo Installing Bennu Portal ...
cd bennu-portal
mvn clean package -q
cd ..
