#!/bin/bash

function stat() {
	echo -e "\n";
	echo -e "\e[1;32m$@\e[0m";
}

stat Installing Bennu Json...
cd bennu-json
mvn clean install -q
cd ..

stat Installing Bennu Maven Plugin...
cd maven/bennu-maven-plugin/
mvn clean install -q
cd ../../

stat Installing Bennu Project...
cd bennu-project
mvn clean install -q
cd ..

stat Installing Bennu Service Annotation...
cd bennu-service
mvn clean install -q
cd ..

stat Installing Bennu Core...
cd bennu-core
mvn clean install -q
cd ..

stat Installing Bennu Dispatch...
cd bennu-dispatch
mvn clean install -q
cd ..

stat Installing Bennu IO...
cd bennu-io
mvn clean install -q
cd ..

stat Installing Bennu IO UI...
cd bennu-io-ui
mvn clean install -q
cd ..


#stat Installing File Support...
#cd file-support
#mvn clean install -q
#cd ..

stat Installing Scheduler ...
cd bennu-scheduler
mvn clean install -q
cd ..

stat Installing Scheduler UI...
cd bennu-scheduler-ui
mvn clean install -q
cd ..




stat Installing Bennu Search...
cd bennu-search
mvn clean install -q
cd ..

#stat Installing Lucene...
#cd lucene
#mvn clean install -q
#cd ..

stat Installing Bennu Portal ...
cd bennu-portal
mvn clean install -q
cd ..

stat Installing Bennu Admin ...
cd bennu-admin
mvn clean install -q
cd ..
