#!/bin/bash

function stat() {
	echo -e "\n";
	echo -e "\e[1;32m$@\e[0m";
}

stat Installing Bennu Json...
cd bennu-json
mvn clean install -q
cd ..

stat Installing Bennu Maven Plugin...
cd maven/bennu-maven-plugin/
mvn clean install -q
cd ../../

stat Installing Bennu Project...
cd bennu-project
mvn clean install -q
cd ..

stat Installing Bennu Service Annotation...
cd bennu-service
mvn clean install -q
cd ..

stat Installing Bennu Core...
cd bennu-core
mvn clean install -q
cd ..

stat Installing Bennu Dispatch...
cd bennu-dispatch
mvn clean install -q
cd ..

stat Installing File Support Plugin...
cd file-support-plugin
mvn clean install -q
cd ..

#stat Installing File Support...
#cd file-support
#mvn clean install -q
#cd ..

stat Installing Scheduler Plugin...
cd scheduler-plugin
mvn clean install -q
cd ..

#stat Installing Scheduler...
#cd scheduler
#mvn clean install -q
#cd ..

stat Installing Lucene Indexing Plugin...
cd lucene-indexing-plugin
mvn clean install -q
cd ..

#stat Installing Lucene...
#cd lucene
#mvn clean install -q
#cd ..

stat Installing Bennu Portal ...
cd bennu-portal
mvn clean install -q
cd ..

stat Installing Bennu Admin ...
cd bennu-admin
mvn clean install -q
cd ..

